<?xml version="1.0" encoding="utf-8"?><Database Name="zzbd" Class="DBdataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Zz-computer;Initial Catalog=zzbd;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="zzbdConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SUser" Member="SUser">
    <Type Name="SUser">
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Admin" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>